language: node_js
node_js:
    - "lts/*"

install:
    - yarn install
    - yarn run build

script:
    - true

cache:
    directories:
        - "node_modules"

notifications:
    email: false

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    target-branch: master
    on:
        branch: develop
